package com.example.wxl.wxlandroidorm.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.wxl.wxlandroidorm.Model.book;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK".
*/
public class bookDao extends AbstractDao<book, Long> {

    public static final String TABLENAME = "BOOK";

    /**
     * Properties of entity book.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Icon = new Property(0, Long.class, "icon", true, "_id");
        public final static Property Booname = new Property(1, String.class, "booname", false, "BOONAME");
        public final static Property Forpeople = new Property(2, String.class, "forpeople", false, "FORPEOPLE");
    }


    public bookDao(DaoConfig config) {
        super(config);
    }
    
    public bookDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: icon
                "\"BOONAME\" TEXT NOT NULL ," + // 1: booname
                "\"FORPEOPLE\" TEXT NOT NULL );"); // 2: forpeople
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, book entity) {
        stmt.clearBindings();
 
        Long icon = entity.getIcon();
        if (icon != null) {
            stmt.bindLong(1, icon);
        }
        stmt.bindString(2, entity.getBooname());
        stmt.bindString(3, entity.getForpeople());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, book entity) {
        stmt.clearBindings();
 
        Long icon = entity.getIcon();
        if (icon != null) {
            stmt.bindLong(1, icon);
        }
        stmt.bindString(2, entity.getBooname());
        stmt.bindString(3, entity.getForpeople());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public book readEntity(Cursor cursor, int offset) {
        book entity = new book( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // icon
            cursor.getString(offset + 1), // booname
            cursor.getString(offset + 2) // forpeople
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, book entity, int offset) {
        entity.setIcon(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBooname(cursor.getString(offset + 1));
        entity.setForpeople(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(book entity, long rowId) {
        entity.setIcon(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(book entity) {
        if(entity != null) {
            return entity.getIcon();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(book entity) {
        return entity.getIcon() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
