package com.example.wxl.wxlandroidorm.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.wxl.wxlandroidorm.Model.book;
import com.example.wxl.wxlandroidorm.Model.jinera;

import com.example.wxl.wxlandroidorm.dao.bookDao;
import com.example.wxl.wxlandroidorm.dao.jineraDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig jineraDaoConfig;

    private final bookDao bookDao;
    private final jineraDao jineraDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(bookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        jineraDaoConfig = daoConfigMap.get(jineraDao.class).clone();
        jineraDaoConfig.initIdentityScope(type);

        bookDao = new bookDao(bookDaoConfig, this);
        jineraDao = new jineraDao(jineraDaoConfig, this);

        registerDao(book.class, bookDao);
        registerDao(jinera.class, jineraDao);
    }
    
    public void clear() {
        bookDaoConfig.clearIdentityScope();
        jineraDaoConfig.clearIdentityScope();
    }

    public bookDao getBookDao() {
        return bookDao;
    }

    public jineraDao getJineraDao() {
        return jineraDao;
    }

}
